# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "example-app/" # Ensure this path is correct
    schedule:
      interval: "daily" # Frequency of update checks

    commit-message:
      prefix: "fix" # Will result in commits like "fix: Update dependencies"
      prefix-development: "chore" # Will result in commits like "chore: Update dependencies for development"
      include: "scope" # Ensure this is either "scope" or "subject"

    open-pull-requests-limit: 2 # Limit to 2 open PR at a time
    rebase-strategy: "auto" # Rebase PRs when necessary
    versioning-strategy: "increase" # Increase version numbers according to semver

    groups: # Group dependencies together for updates
      react-packages: # Name of the group
        patterns: # Match dependencies that contain these strings
          - "react" # Will match "react" and "react-dom" etc.
        update-types: # Types of updates to consider for dependencies in this group
          - "patch"
          - "minor"
      other-dependencies: 
        patterns:
          - "web-vitals"

