# .github/release.yml

changelog:
  exclude:
    labels:
    - ignore-for-release
    authors:
    - ${{ env.authors }}
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Dependency Updates 📦
      labels:
        - dependencies
        - dependency-update
    - title: Security Updates 🔒
      labels:
        - security
        - security-update
    - title: Documentation Changes 📖
      labels:
        - documentation
        - docs
    - title: Bug Fixes 🐛
      labels:
        - Semver-Patch
        - bug
    - title: Other Changes
      labels:
        - internal
        - refactor
        - test
        - chore
        - ci
        - build
        - performance
        - style
        - other