name: Centralized Security Library Workflow

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
    security-events: write

jobs:
    codeql:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                language: [ 'javascript-typescript' ]

        env:
            CODEQL_DB_PATH: ${{ github.workspace }}/codeql-dbs/${{ github.repository }}
            SARIF_OUTPUT_PATH: /temp/${{ github.repository }}-${{ matrix.language }}.sarif
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Create CodeQL database directory
            run: mkdir -p ${{ env.CODEQL_DB_PATH }}

          - name: Set up CodeQL
            uses: github/codeql-action/init@v3
            with:
                languages: ${{ matrix.language }}
                source-root: .
                db-location: ${{ env.CODEQL_DB_PATH }}

          # - name: Initialize CodeQL database
          #   run: codeql database init --language=${{ matrix.language }} --source-root . --begin-tracing ${{ env.CODEQL_DB_PATH }}

          - name: Build app with build command
            run: |
              cd ./datatable-app/
              npm install
              npm run build

          - name: Finalize CodeQL database
            run: codeql database finalize ${{ env.CODEQL_DB_PATH }}

          - name: Analyze CodeQL database
            run: codeql database analyze ${{ env.CODEQL_DB_PATH }} ${{ matrix.language }}-code-scanning.qls --sarif-category=${{ matrix.language}} --format=sarif-latest --output=$${{ env.SARIF_OUTPUT_PATH }}

          - name: Upload CodeQL results
            run: echo "${{ env.TOKEN }}" | codeql github upload-results --repository=${{ github.repository }} --ref=${{ github.ref }} --commit=${{ github.sha }} --sarif=${{ env.SARIF_OUTPUT_PATH }} --github-auth-stdin