name: Centralized Security Library Workflow

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
    security-events: write

jobs:
    codeql:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                language: [ 'javascript-typescript' ]

        env:
            CODEQL_DB_PATH: ${{ github.workspace }}/codeql-dbs/${{ github.repository }}
            SARIF_OUTPUT_PATH: /${{ github.workspace }}/${{ github.repository }}-${{ matrix.language }}.sarif
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Create CodeQL database directory
            run: mkdir -p ${{ env.CODEQL_DB_PATH }}

          - name: Set up CodeQL
            uses: github/codeql-action/init@v3
            with:
                languages: ${{ matrix.language }}
                source-root: .
                db-location: ${{ env.CODEQL_DB_PATH }}

          - name: Build app with build command
            run: |
              cd ./datatable-app/
              npm install
              npm run build

          - name: Analyze CodeQL database
            uses: github/codeql-action/analyze@v3
            with:
                output: ${{ env.SARIF_OUTPUT_PATH }}